### ISSUE TITLE
How to authenticate with Azure ? 

### ISSUE THREAD

**Issue by peterinfra** [cloudquery/cq-provider-azure#4]
```
providers:
    - name: azure
      subscriptions:
        - "<redacted>"
      version: latest
      resources:
        - name: resources.groups
        - name: sql.servers
        - name: sql.databases
        - name: postgresql.servers
        - name: mysql.servers
        - name: compute.disks
        - name: keyvault.vaults
        - name: network.virtual_networks
 ```
  Running fetch
```
cloudquery fetch --driver postgresql --dsn "host=localhost user=postgres password=<redacted> DB.name=postgres port=5432"
10:25AM INF logging configured consoleLog=true fileLogging=true fileName=cloudquery.log jsonLogOutput=false logDirectory=. maxAgeInDays=3 maxBackups=3 maxSizeMB=30 verbose=false
10:25AM INF requesting provider initialize provider=azure version=latest
10:25AM INF Creating tables if needed @module=azure timestamp=2021-03-26T10:25:43.543-0700
10:25AM INF requesting provider fetch provider=azure version=latest
Error: rpc error: code = Unknown desc = azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/<redacted>/resourcegroups?api-version=2020-06-01: StatusCode=0 -- Original Error: the MSI endpoint is no
```
